# Generated by Django 5.1.4 on 2025-01-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Not Approved')], default=False),
        ),
    ]
